services:
    pushDevices:
        class: ekreative\AWSPushBundle\Service\Devices
        arguments:
          - "@snsClient"
          - "%ekreative_aws_push.platforms%"
    pushMessages:
        class: ekreative\AWSPushBundle\Service\Messages
        arguments:
          - "@snsClient"
          - "%ekreative_aws_push.platforms%"
          - "@logger"
    snsClient:
        class: Aws\Sns\SnsClient
        factory_class: Aws\Sns\SnsClient
        factory_method: factory
        arguments:
          -
            key: "%ekreative_aws_push.aws.key%"
            secret: "%ekreative_aws_push.aws.secret%"
            region: "%ekreative_aws_push.aws.region%"
