language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer selfupdate
    - composer install --prefer-source
    - echo 'hhvm.libxml.ext_entity_whitelist = file,http'  >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: ./vendor/bin/phpunit
