parameters:
    mcfedr_aws_push.platforms: []
    mcfedr_aws_push.aws.key: ''
    mcfedr_aws_push.aws.secret: ''
    mcfedr_aws_push.aws.region: ''
    mcfedr_aws_push.debug: false
    mcfedr_aws_push.topic_name: ''

services:
    mcfedr_aws_push.devices:
        class: Mcfedr\AwsPushBundle\Service\Devices
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"

    mcfedr_aws_push.messages:
        class: Mcfedr\AwsPushBundle\Service\Messages
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@logger"
          - "%mcfedr_aws_push.debug%"

    mcfedr_aws_push.api:
        class: Mcfedr\AwsPushBundle\Controller\APIController
        arguments:
          - "@mcfedr_aws_push.devices"
          - "@mcfedr_aws_push.messages"
          - "@mcfedr_aws_push.topics"
          - "%mcfedr_aws_push.topic_name%"
          - "@logger"
          - "@security.context"

    mcfedr_aws_push.command.subscribe:
        class: Mcfedr\AwsPushBundle\Command\SubscribeTopicsCommand
        arguments:
          - "@mcfedr_aws_push.topics"
          - "%mcfedr_aws_push.topic_name%"
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.command.enable:
        class: Mcfedr\AwsPushBundle\Command\EnableAllCommand
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.command.remove:
        class: Mcfedr\AwsPushBundle\Command\RemoveDisabledCommand
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.command.subscribe:
          class: Mcfedr\AwsPushBundle\Command\ListTopicArnsCommand
          arguments:
            - "@mcfedr_aws_push.topics"
            - "%mcfedr_aws_push.topic_name%"
            - "@logger"
          tags:
            -  { name: console.command }

    mcfedr_aws_push.sns_client:
        class: Aws\Sns\SnsClient
        factory_class: Aws\Sns\SnsClient
        factory_method: factory
        arguments:
          -
            key: "%mcfedr_aws_push.aws.key%"
            secret: "%mcfedr_aws_push.aws.secret%"
            region: "%mcfedr_aws_push.aws.region%"
