parameters:
    mcfedr_aws_push.platforms: []
    mcfedr_aws_push.aws.key: ''
    mcfedr_aws_push.aws.secret: ''
    mcfedr_aws_push.aws.region: ''
    mcfedr_aws_push.debug: false
    mcfedr_aws_push.topic_arn: ''

services:
    mcfedr_aws_push.devices:
        class: Mcfedr\AwsPushBundle\Service\Devices
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"

    mcfedr_aws_push.messages:
        class: Mcfedr\AwsPushBundle\Service\Messages
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "%mcfedr_aws_push.debug%"
          - "@?logger"

    mcfedr_aws_push.topics:
        class: Mcfedr\AwsPushBundle\Service\Topics
        arguments:
            - "@mcfedr_aws_push.sns_client"
            - "@mcfedr_aws_push.messages"
            - "%mcfedr_aws_push.debug%"
            - "@?logger"

    mcfedr_aws_push.command.subscribe:
        class: Mcfedr\AwsPushBundle\Command\SubscribeTopicsCommand
        arguments:
          - "%mcfedr_aws_push.topic_arn%"
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.command.enable:
        class: Mcfedr\AwsPushBundle\Command\EnableAllCommand
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.command.remove:
        class: Mcfedr\AwsPushBundle\Command\RemoveDisabledCommand
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.sns_client:
        class: Aws\Sns\SnsClient
        arguments:
          -
            version: "2010-03-31"
            region: "%mcfedr_aws_push.aws.region%"
            credentials:
               key: "%mcfedr_aws_push.aws.key%"
               secret: "%mcfedr_aws_push.aws.secret%"
